on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      pnpm-cache-path: ${{ steps.pnpm-cache-path.outputs.store }}
    steps:
      - uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - name: Get pnpm store directory
        run: |
          echo "store=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ steps.pnpm-cache-path.outputs.store }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}

      - name: Install packages
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{needs.setup.outputs.pnpm-cache-path}}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
      - name: tsc
        run: pnpm tsc
      - name: lint, prettier
        run: pnpm turbo lint prettier:check
