name: CI

on:
  push:
    branches-ignore: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml

  build:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Get pnpm cache directory path
        id: pnpm-cache-path
        run: echo "dir=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ steps.pnpm-cache-path.outputs.dir }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Run build
        run: pnpm build
        env:
          NEXT_PUBLIC_AIRTABLE_PAT: ${{ secrets.NEXT_PUBLIC_AIRTABLE_PAT }}
          NEXT_PUBLIC_AIRTABLE_BASE_INQUIRYFORM: ${{ secrets.NEXT_PUBLIC_AIRTABLE_BASE_INQUIRYFORM }}
          NEXT_PUBLIC_AIRTABLE_TABLE_INQUIRYFORM: ${{ secrets.NEXT_PUBLIC_AIRTABLE_TABLE_INQUIRYFORM }}
          NEXT_PUBLIC_JSONLINK_API_KEY: ${{secrets.NEXT_PUBLIC_JSONLINK_API_KEY}}
