name: publish

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml

  build:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/configure-pages@v5
        with:
          # Automatically inject basePath in next.config.js
          static_site_generator: next
      - name: Get pnpm cache directory path
        id: pnpm-cache-path
        run: echo "store=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ steps.pnpm-cache-path.outputs.store }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: build
        run: pnpm build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_AIRTABLE_PAT: ${{ secrets.NEXT_PUBLIC_AIRTABLE_PAT }}
          NEXT_PUBLIC_AIRTABLE_BASE_INQUIRYFORM: ${{ secrets.NEXT_PUBLIC_AIRTABLE_BASE_INQUIRYFORM }}
          NEXT_PUBLIC_AIRTABLE_TABLE_INQUIRYFORM: ${{ secrets.NEXT_PUBLIC_AIRTABLE_TABLE_INQUIRYFORM }}
          NEXT_PUBLIC_JSONLINK_API_KEY: ${{secrets.NEXT_PUBLIC_JSONLINK_API_KEY}}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
