name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install packages
        run: yarn install --immutable
      - name: Run tsc
        run: yarn tsc
      - name: Run lint
        run: yarn lint
      - name: Run prettier
        run: yarn prettier
      - name: Run build
        env: # Or as an environment variable
          LINKPREVIEW_API_KEY: ${{ secrets.LINKPREVIEW_API_KEY }}
        run: yarn build
